apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cims-environments
  namespace: argocd
  labels:
    app: cims
spec:
  generators:
  - list:
      elements:
        - name: cims-dev
          branch: dev
          namespace: cims-dev
          environment: development
        - name: cims-prod
          branch: main
          namespace: cims
          environment: production
  template:
    metadata:
      name: '{{name}}'
      labels:
        app: cims
        environment: '{{environment}}'
    spec:
      project: default
      source:
        repoURL: https://gitlab.com/cims/microservice.git
        targetRevision: '{{branch}}'
        path: k8s
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - ApplyOutOfSyncOnly=true
      revisionHistoryLimit: 10
