apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cims
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitlab.com/cims/microservice.git
    targetRevision: main
    path: k8s
    directory:
      recurse: true
      exclude: "{argocd-app.yaml,deploy-minikube.sh,README.md}"
  destination:
    server: https://kubernetes.default.svc
    namespace: cims
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
